version: '3.2'

services:
  db:
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    build:
      context: ./docker
      dockerfile: db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT:-54320}:${DB_PORT:-5432}"

  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/src:/src
    ports:
      - "${API_EXPOSE_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - .env
    depends_on:
      - db
    tty: true
    # コンテナ立ち上げ時にスクリプトの実行
    command: sh -c "chmod 755 /src/entrypoint.sh && /src/entrypoint.sh"

  frontend:
    container_name: front
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend/src:/src
    ports:
      - "${NODE_EXPOSE_PORT:-3000}:${NODE_PORT:-3000}"
    env_file:
      - .env
    depends_on:
      - backend
    tty: true

volumes:
  postgres_data:
    driver: local
