version: '3.2'

services:
  app:
    container_name: django_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    volumes:
      - ./src/:/app
    ports:
      - "${APP_EXPOSE_PORT:-50000}:${APP_PORT:-5000}"
    depends_on:
      - db

  db:
    container_name: django_db
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT:-54320}:${DB_PORT:-5432}"

volumes:
  postgres_data:
    driver: local
