version: '3.2'

services:
  db:
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT:-54320}:${DB_PORT:-5432}"

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "${API_EXPOSE_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - .env
    depends_on:
      - db
    tty: true
    # コンテナ立ち上げ時にスクリプトの実行
    command: sh -c "chmod 755 /src/entrypoint.sh && /src/entrypoint.sh"

volumes:
  postgres_data:
    driver: local
