version: '3.2'

services:
  backend:
    container_name: django
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    tty: true
    volumes:
      - ./backend/:/backend
    ports:
      - "${API_EXPOSE_PORT:-8000}:${API_PORT:-8000}"
    depends_on:
      - db
    command: python manage.py runserver

  db:
    container_name: postgres
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT:-54320}:${DB_PORT:-5432}"

volumes:
  postgres_data:
    driver: local
