# Generated by Django 4.1.6 on 2023-02-16 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('attribute', models.PositiveSmallIntegerField(choices=[(1, '成人'), (2, '大学'), (3, '高校'), (4, '中学'), (5, '少年')], verbose_name='属性')),
                ('team_type', models.PositiveSmallIntegerField(choices=[(1, '硬式'), (2, '軟式'), (3, '準硬式'), (4, 'ソフトボール')], verbose_name='種別')),
                ('prefecture_code', models.CharField(max_length=30, verbose_name='都道府県コード')),
                ('prefecture_name', models.CharField(max_length=10, verbose_name='都道府県名')),
                ('city_code', models.CharField(max_length=50, verbose_name='市区町村コード')),
                ('city_name', models.CharField(max_length=50, verbose_name='市区町村名')),
                ('name_ja', models.CharField(max_length=250, verbose_name='チーム名：日本語')),
                ('name_en', models.CharField(max_length=250, verbose_name='チーム名：英名')),
                ('name_kana', models.CharField(max_length=250, verbose_name='チーム名：カナ')),
                ('home_ground', models.CharField(blank=True, max_length=250, null=True, verbose_name='ホームグラウンド')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='スローガン')),
                ('introduction', models.TextField(blank=True, max_length=1000, null=True, verbose_name='チーム紹介文')),
                ('started_date', models.DateField(verbose_name='結成日')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
