# Generated by Django 4.1.6 on 2023-02-16 06:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'このユーザー名は既に使用されています。'}, help_text='※150文字以下の英数字、一部の記号で入力してください。', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザーネーム')),
                ('is_staff', models.BooleanField(default=False, help_text='ユーザーがこの管理サイトにログインできるかどうかを判別します。', verbose_name='ユーザーステータス')),
                ('is_active', models.BooleanField(default=True, help_text='このユーザーをアクティブとして扱うかどうかを指定します。アカウントを削除する代わりに、当該フラグを切り替えてください。', verbose_name='アクティブユーザ')),
                ('first_name', models.CharField(max_length=100, verbose_name='名前')),
                ('last_name', models.CharField(max_length=100, verbose_name='苗字')),
                ('first_name_kana', models.CharField(max_length=100, verbose_name='名前：カナ')),
                ('last_name_kana', models.CharField(max_length=100, verbose_name='苗字：カナ')),
                ('first_name_en', models.CharField(max_length=200, verbose_name='名前：英語')),
                ('last_name_en', models.CharField(max_length=200, verbose_name='苗字：英語')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
