# Generated by Django 4.1.6 on 2023-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='このユーザーをアクティブとして扱うかどうかを指定します。アカウントを削除する代わりに、この選択状態を切り替えてください。', verbose_name='アクティブユーザ'),
        ),
    ]
